FROM debian:testing
RUN apt-get update -q=2 \
    && apt-get install -qy \
        black \
        codespell \
        flake8 \
        make \
        mypy \
        python3 \
        python3-pytest \
        python3-pytest-cov \
        python3-pytest-mock \
    && true

# vim: ft=dockerfile
